### ISSUE TITLE
Too many defense cards can halt game

### ISSUE THREAD

**Issue by jcbrockschmidt** [TheUnderscores/card-fight-thingy#11]
If a player ends up with all defense cards and has there defense stack completely full, the game will come to a halt. The game will not allow a player to continue until they use a card. However, in an instance such as this one, the player cannot use a card.

Possible solutions:
1) Give players the option to redraw a card. Uses up a turn.
2) Give players the option to get a whole new hand. Uses up a turn.

I am more in favor of the 2nd.

**Comment by RobertCochran** [comment]
I thought we were doing to go with a discard system. It just never got implemented.

**Comment by jcbrockschmidt** [comment]
Oh, slipped my mind. Do you prefer the first or the second method, though?

**Comment by RobertCochran** [comment]
I think 'toss hand' is a bit much. I'd much prefer 'toss a card'.

**Comment by RobertCochran** [comment]
Left this alone for too long. Discard has long since been implemented.
Closing.
